DELETE FROM status;

INSERT INTO status (name) VALUES ('UNDER_CONSIDERATION'), ('RECRUITER_INTERVIEW'), ('TECHNICAL_SPECIALIST_INTERVIEW'), ('RECRUITER_INTERVIEW_PASSED'), ('TECHNICAL_SPECIALIST_INTERVIEW_PASSED'), ('REFUSED'), ('ACCEPTED'), ('REJECTED'), ('AWAITING');
